CREATE TABLE PROVEEDORES(
COD_PROVEEDOR VARCHAR2(10) NOT NULL,
TXT_NOMBRE VARCHAR2(50) NOT NULL,
TXT_NOMBRE VARCHAR2(50) NOT NULL,
TXT_APELLIDO1 VARCHAR2(50) NOT NULL,
TXT_APELLIDO2 VARCHAR2(50),
COD_DOCUM VARCHAR2(10) NOT NULL
);
COMMENT ON TABLE PROVEEDORES IS 'TABLA DE PROVEEDORES';
COMMENT ON COLUMN PROVEEDORES.COD_PROVEEDOR IS 'CODIGO DE CLIENTE';
COMMENT ON COLUMN PROVEEDORES.TXT_NOMBRE IS 'NOMBRE DEL CLIENTE';
COMMENT ON COLUMN PROVEEDORES.TXT_APELLIDO1 IS 'APELLIDO 1';
COMMENT ON COLUMN PROVEEDORES.TXT_APELLIDO2 IS 'APELLIDO 2';
COMMENT ON COLUMN PROVEEDORES.COD_DOCUM IS 'DOCUMENTO DE IDENTIDAD';

CREATE UNIQUE INDEX PK_PROVEEDORES ON PROVEEDORES
       (COD_PROVEEDOR ASC);

ALTER TABLE PROVEEDORES
      ADD CONSTRAINT PK_PROVEEDORES
      PRIMARY KEY(COD_PROVEEDOR)
      USING INDEX PK_PROVEEDORES;

CREATE UNIQUE INDEX AK_PROVEEDORES ON PROVEEDORES
       (COD_DOCUM ASC);
