SET DEFINE ON
SET VERIFY ON
SET ECHO OFF
SPOOL "C:\MDSQL_JAVA\scripts\pruebaEscriptTablaAAA\20230217_11_30_MDSQL_SMD_DD_SD.log"
DEFINE DAT_SMD_LD_U64K=DAT_SMD_LD_U64K
DEFINE GRADOPARAL=8
DEFINE IND_SMD_LD_U64K=IND_SMD_LD_U64K
DEFINE USROWN=SMD
@"C:\MDSQL_JAVA\scripts\pruebaEscriptTablaAAA\20230217_11_30_MDSQL_SMD_DD_SD.sql"
SPOOL OFF
EXIT
