--------------------------------------------------------
--  DDL for Table AVISO
--------------------------------------------------------

  CREATE TABLE "SAPIENS"."AVISO" 
   (	"COD_PROYECTO" VARCHAR2(30 BYTE), 
	"COD_NIVEL_AVISO" NUMBER(1,0), 
	"DES_NIVEL_AVISO" VARCHAR2(7 BYTE), 
	"COD_AVISO" NUMBER, 
	"DES_AVISO" VARCHAR2(100 BYTE), 
	"TXT_AVISO" VARCHAR2(500 BYTE), 
	"COD_PETICION" VARCHAR2(25 BYTE), 
	"FEC_ALTA" DATE DEFAULT sysdate, 
	"COD_USR_ALTA" VARCHAR2(8 BYTE), 
	"MCA_HABILITADO" VARCHAR2(1 BYTE), 
	"FEC_ACTU" DATE DEFAULT sysdate, 
	"COD_USR" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
