--------------------------------------------------------
--  DDL for Table BBDD
--------------------------------------------------------

  CREATE TABLE "SAPIENS"."BBDD" 
   (	"COD_PROYECTO" VARCHAR2(30 BYTE), 
	"NOM_BBDD" VARCHAR2(30 BYTE), 
	"NOM_ESQUEMA" VARCHAR2(30 BYTE), 
	"NOM_BBDD_HIS" VARCHAR2(30 BYTE), 
	"NOM_ESQUEMA_HIS" VARCHAR2(30 BYTE), 
	"MCA_DEFECTO" VARCHAR2(1 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
