--------------------------------------------------------
--  DDL for Table DET_VALIDACION
--------------------------------------------------------

  CREATE TABLE "SAPIENS"."DET_VALIDACION" 
   (	"NUM_VALIDACION" NUMBER, 
	"NUM_ELEM_VALID" NUMBER(6,0), 
	"DES_ELEMENTO" VARCHAR2(50 BYTE), 
	"NOM_ELEMENTO" VARCHAR2(30 BYTE), 
	"TIP_DATO" VARCHAR2(30 BYTE), 
	"NUM_LONGITUD" NUMBER, 
	"NUM_DECIMAL" NUMBER, 
	"COD_ESTADO_VALID" NUMBER(2,0), 
	"TXT_DES_VALID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_PERM_SAPIENS" ;
