--------------------------------------------------------
--  DDL for Table ELEMENTO_NORMA
--------------------------------------------------------

  CREATE TABLE "SAPIENS"."ELEMENTO_NORMA" 
   (	"COD_NORMA" NUMBER(2,0), 
	"DES_NORMA" VARCHAR2(50 BYTE), 
	"COD_ELEMENTO" NUMBER(3,0), 
	"DES_ELEMENTO" VARCHAR2(50 BYTE), 
	"VAL_TAM_MAX" NUMBER(2,0), 
	"TXT_FORMATO" VARCHAR2(200 BYTE), 
	"COD_USR" VARCHAR2(8 BYTE), 
	"FEC_ACTU" DATE, 
	"TXT_FORMATO_DES1" VARCHAR2(200 BYTE), 
	"TXT_FORMATO_DES2" VARCHAR2(200 BYTE), 
	"TXT_FORMATO_DES3" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_PERM_SAPIENS" ;
