--------------------------------------------------------
-- Archivo creado  - sábado-abril-01-2023   
--------------------------------------------------------
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/T_R_SCRIPT_LANZA.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SEQ_ERROR.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SEQ_ID_LINEA_SCRIPT.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SEQ_ID_PROCESO.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SEQ_ID_SCRIPT.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SEQ_ID_SCRIPT_LANZA.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SEQ_NUM_ORDEN.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/AVISO.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/BBDD.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/CAMPO_GLOSARIO.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/DET_VALIDACION.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/ELEMENTO.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/ELEMENTO_NORMA.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/ERRORES.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/GLOSARIO.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/LINEAS_SCRIPT.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/MODELO.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/NORMA.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/OBJ_HIS.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/PARTICULA.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/PARTICULA_NORMA.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/PROCESO.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SCRIPT.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SCRIPTS_LANZA.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SUBPROYECTO.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/TIPO_DATO.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/VALIDA_PARTICULA.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/VAL_PARTICULA.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/AVISO_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/BBDD_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/CAMPO_GLOSARIO_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/DET_VALIDACION_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/ELEMENTO_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/ELEMENTO_NORMA_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/ERRORES_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/GLOSARIO_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/LINEAS_SCRIPT_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/MODELO_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/NORMA_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/OBJ_HIS_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/PARTICULA_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/PARTICULA_NORMA_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/PROCESO_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SCRIPT_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SCRIPTS_LANZA_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SUBPROYECTO_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/TIPO_DATO_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/VALIDA_PARTICULA_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/VAL_PARTICULA_DATA_TABLE.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/GLOSARIOS_PK.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/LINEAS_SCRIPT_PK.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/PK_ID.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/PROCESO_PK.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SM2_K_LD_MDSQL_1.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SM2_K_LD_MDSQL_2.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/CREATE_SCRIPT_LANZA.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/PROCESO_CONSTRAINT.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/LINEAS_SCRIPT_CONSTRAINT.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/AVISO_CONSTRAINT.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SCRIPT_CONSTRAINT.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/GLOSARIO_CONSTRAINT.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/LINEAS_SCRIPT_REFCONSTRAINT.sql
@/home/federico/workspace-jboss/AppSapiens/BD/MDSQL/SCRIPT_REFCONSTRAINT.sql
