--------------------------------------------------------
--  DDL for Table OBJ_HIS
--------------------------------------------------------

  CREATE TABLE "SAPIENS"."OBJ_HIS" 
   (	"COD_PROYECTO" VARCHAR2(30 BYTE), 
	"LINEA" VARCHAR2(500 BYTE), 
	"NOM_OBJETO" VARCHAR2(30 BYTE), 
	"TIP_OBJETO" VARCHAR2(20 BYTE), 
	"MCA_VIG" VARCHAR2(1 BYTE), 
	"MCA_HIS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
