--------------------------------------------------------
--  DDL for Table PARTICULA_NORMA
--------------------------------------------------------

  CREATE TABLE "SAPIENS"."PARTICULA_NORMA" 
   (	"COD_NORMA" NUMBER(2,0), 
	"DES_NORMA" VARCHAR2(50 BYTE), 
	"COD_ELEMENTO" NUMBER(3,0), 
	"DES_ELEMENTO" VARCHAR2(50 BYTE), 
	"NUM_PARTICULA" NUMBER(2,0), 
	"DES_NUM_PART" VARCHAR2(50 BYTE), 
	"MCA_OBLIGATORIA" VARCHAR2(1 BYTE), 
	"MCA_VALIDACION" VARCHAR2(1 BYTE), 
	"VAL_TAM_MIN" NUMBER(2,0), 
	"VAL_TAM_MAX" NUMBER(2,0), 
	"MCA_VAL_PADRE" VARCHAR2(1 BYTE), 
	"NUM_PART_PADRE" NUMBER(2,0), 
	"COD_USR" VARCHAR2(8 BYTE), 
	"FEC_ACTU" DATE, 
	"TIP_VALIDACION" VARCHAR2(20 BYTE), 
	"COD_PARTICULA" NUMBER(5,0), 
	"DES_PARTICULA" VARCHAR2(80 BYTE), 
	"MCA_PROYECTO" VARCHAR2(1 BYTE), 
	"TXT_FORMATO_PART" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_PERM_SAPIENS" ;
