--------------------------------------------------------
--  Constraints for Table PROCESO
--------------------------------------------------------

  ALTER TABLE "SAPIENS"."PROCESO" MODIFY ("FEC_INICIO" NOT NULL ENABLE);
  ALTER TABLE "SAPIENS"."PROCESO" MODIFY ("ID_PROCESO" NOT NULL ENABLE);
  ALTER TABLE "SAPIENS"."PROCESO" ADD CONSTRAINT "PROCESO_PK" PRIMARY KEY ("ID_PROCESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
