--------------------------------------------------------
--  DDL for Table PROCESO
--------------------------------------------------------

  CREATE TABLE "SAPIENS"."PROCESO" 
   (	"COD_PROYECTO" VARCHAR2(30 BYTE), 
	"ID_PROCESO" NUMBER, 
	"COD_PETICION" VARCHAR2(25 BYTE), 
	"COD_USR_PETICION" VARCHAR2(8 BYTE), 
	"FEC_INICIO" DATE DEFAULT SYSDATE, 
	"COD_USR" VARCHAR2(8 BYTE), 
	"COD_ESTADO_PROC" NUMBER(1,0), 
	"DES_ESTADO_PROC" VARCHAR2(20 BYTE), 
	"MCA_INICIAL" VARCHAR2(1 BYTE), 
	"TXT_DESCRIPCION" VARCHAR2(500 BYTE), 
	"TXT_OBS_ENTREGA" VARCHAR2(500 BYTE), 
	"MCA_ERRORES" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
