--------------------------------------------------------
--  Constraints for Table SCRIPT
--------------------------------------------------------

  ALTER TABLE "SAPIENS"."SCRIPT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SAPIENS"."SCRIPT" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SAPIENS"."SCRIPT" MODIFY ("RUTA" NOT NULL ENABLE);
  ALTER TABLE "SAPIENS"."SCRIPT" ADD CONSTRAINT "SCRIPT_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "SAPIENS"."PK_ID" ON "SAPIENS"."SCRIPT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "SAPIENS"."SCRIPT" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "SAPIENS"."SCRIPT" MODIFY ("ID_PROCESO" NOT NULL ENABLE);
