--------------------------------------------------------
--  DDL for Table SUBPROYECTO
--------------------------------------------------------

  CREATE TABLE "SAPIENS"."SUBPROYECTO" 
   (	"COD_PROYECTO" VARCHAR2(30 BYTE), 
	"COD_SUB_PROY" VARCHAR2(30 BYTE), 
	"DES_SUB_PROY" VARCHAR2(150 BYTE), 
	"COD_USR" VARCHAR2(8 BYTE), 
	"FEC_ACTU" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_PERM_SAPIENS" ;
