--------------------------------------------------------
--  DDL for Table VAL_PARTICULA
--------------------------------------------------------

  CREATE TABLE "SAPIENS"."VAL_PARTICULA" 
   (	"COD_PARTICULA" NUMBER(5,0), 
	"VAL_PARTICULA" VARCHAR2(10 BYTE), 
	"DES_VAL_PART" VARCHAR2(60 BYTE), 
	"COD_PROYECTO" VARCHAR2(30 BYTE), 
	"COD_SUB_PROY" VARCHAR2(30 BYTE), 
	"VAL_PART_PADRE" VARCHAR2(10 BYTE), 
	"COD_USR" VARCHAR2(8 BYTE), 
	"FEC_ACTU" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_PERM_SAPIENS" ;
