--------------------------------------------------------
--  DDL for Table VALIDA_PARTICULA
--------------------------------------------------------

  CREATE TABLE "SAPIENS"."VALIDA_PARTICULA" 
   (	"NUM_PARTICULA" NUMBER(*,0), 
	"TXT_VALIDACION" VARCHAR2(100 BYTE), 
	"TXT_VALOR" VARCHAR2(100 BYTE), 
	"DES_ESTADO_VALID" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_PERM_SAPIENS" ;
