SET DEFINE ON
SET VERIFY ON
SET ECHO OFF
SPOOL "C:\workspaceEsoluzion\AppSapiens\SQL/SMD_Tabla_A - saltos_RECHAZADO_RECHAZADO.sql.log"
DEFINE DAT_SMD_LD_U64K=DAT_SMD_LD_U64K
DEFINE IND_SMD_LD_U64K=IND_SMD_LD_U64K
DEFINE USROWN=HR
@"C:\workspaceEsoluzion\AppSapiens\SQL/SMD_Tabla_A - saltos_RECHAZADO_RECHAZADO.sql"
SPOOL OFF
EXIT
