SELECT 
	b2.JOB_INSTANCE_ID, JOB_NAME AS JOB, DATE_FORMAT(CREATE_TIME, '%d-%m-%Y %H:%i:%s') as CREATION, 
	TRUNCATE((end_time - start_time), 2) as DURATION,
   	STATUS
FROM 
	BATCH_JOB_EXECUTION b1 inner join BATCH_JOB_INSTANCE b2
	on b1.JOB_INSTANCE_ID = b2.JOB_INSTANCE_ID
ORDER BY 
	CREATE_TIME DESC
LIMIT 1;
